//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clase2403.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles_Usuarios
    {
        public int Id_Rol_Usuario { get; set; }
        public Nullable<int> Id_Usuario { get; set; }
        public string Tipo_Rol { get; set; }
    
        public virtual tb_usuarios tb_usuarios { get; set; }
    }
}
